name: Bump GLPI Agent Cask

on:
  schedule:
    - cron: '0 0 * * *' # Check for updates daily
  workflow_dispatch:

jobs:
  bump:
    runs-on: macos-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Setup Homebrew
        uses: Homebrew/actions/setup-homebrew@main

      - name: Configure Git user
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Fetch latest version
        id: get_version
        run: |
          LATEST_VERSION=$(curl -sL -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/glpi-project/glpi-agent/releases/latest | jq -r .tag_name | sed 's/^v//')
          echo "version=$LATEST_VERSION" >> $GITHUB_OUTPUT

      - name: Bump Cask
        run: |
          brew bump-cask-pr --write-only --commit --version=${{ steps.get_version.outputs.version }} eduardomozart/glpi-agent/glpi-agent || true
          
          NIGHTLY_VERSION=$(curl -sL https://nightly.glpi-project.org/glpi-agent/ | grep -Eo 'GLPI-Agent-[0-9.]+-[a-z0-9]+_x86_64\.pkg' | head -n 1 | sed -E 's/GLPI-Agent-(.*)_x86_64\.pkg/\1/')
          brew bump-cask-pr --write-only --commit --version=$NIGHTLY_VERSION eduardomozart/glpi-agent/glpi-agent-nightly || true
          
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/eduardomozart/homebrew-glpi-agent.git HEAD:main
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
