name: Bump GLPI Agent Cask

on:
  schedule:
    - cron: '0 0 * * *' # Check for updates daily
  workflow_dispatch:

jobs:
  bump:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Bump Cask
        uses: dawidd6/action-homebrew-bump-cask@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          cask: glpi-agent
          tap: eduardomozart/glpi-agent
